import {
  DEMO_OPERATORS,
  DEMO_PILOTS,
  buildDemoCurrencyRecords,
  type IsoDate,
  type OperatorId,
} from '@dnca/domain';
import {
  buildCrewCurrencySnapshot,
  type CategoryBlock,
  type CurrencyRow,
  type PilotBlock,
} from '@dnca/exports';

export const dynamic = 'force-dynamic';

interface PageProps {
  searchParams: Promise<{ operatorId?: string }>;
}

export default async function CrewCurrencySnapshotPage({ searchParams }: PageProps) {
  const { operatorId } = await searchParams;
  const operator =
    (operatorId
      ? DEMO_OPERATORS.find((o) => o.id === (operatorId as OperatorId))
      : DEMO_OPERATORS[0]) ?? DEMO_OPERATORS[0]!;
  const asOfDate = new Date();
  const asOf = asOfDate.toISOString().slice(0, 10) as IsoDate;
  const pilots = DEMO_PILOTS.filter((p) => p.operatorId === operator.id);
  const records = buildDemoCurrencyRecords(asOfDate).filter((r) => r.operatorId === operator.id);

  const data = buildCrewCurrencySnapshot({
    operator,
    pilots,
    currencyRecords: records,
    asOf,
    generatedAt: asOfDate,
  });

  return (
    <>
      <PrintStyle />
      <div className="print-root font-sans text-slate-800">
        <PrintToolbar asOf={asOf} operatorTradingName={operator.tradingName} />
        <article className="snapshot mx-auto max-w-3xl bg-white p-10 print:m-0 print:max-w-none print:p-0">
          <header className="flex items-end justify-between border-b-2 border-amber-500 pb-3">
            <div>
              <h1 className="text-lg font-bold text-navy-900">DN Consultancy Aviation</h1>
              <div className="text-[10px] text-slate-600">
                Flight Crew Training Suite · KCARs 2025-aligned
              </div>
            </div>
            <div className="text-right">
              <div className="text-sm font-bold text-navy-900">CREW CURRENCY SNAPSHOT</div>
              <div className="text-[10px] text-slate-600">As of {data.asOf}</div>
            </div>
          </header>

          <section className="my-4 grid grid-cols-2 gap-x-6 gap-y-2 rounded bg-slate-100 px-4 py-3 text-[11px]">
            <Meta label="Operator" value={data.operator.legalName} />
            <Meta label="AOC No." value={data.operator.aocNumber} />
            <Meta label="Accountable Manager" value={data.operator.accountableManagerName} />
            <Meta label="Pilots in snapshot" value={String(data.pilots.length)} />
          </section>

          <section className="my-4 rounded border border-slate-200 p-3 text-[10px] text-slate-700">
            <strong>Operator-wide totals across all items:</strong> {data.operatorTotals.CURRENT}{' '}
            current · {data.operatorTotals.CAUTION} caution · {data.operatorTotals.ACTION} action ·{' '}
            {data.operatorTotals.EXPIRED} expired · {data.operatorTotals.NOT_APPLICABLE} N/A
          </section>

          {data.pilots.map((p) => (
            <PilotSection key={p.pilot.id} block={p} />
          ))}

          <footer className="mt-8 border-t border-slate-200 pt-3 text-[9px] text-slate-500">
            <div>
              Generated by DNCA Fokker Training Suite
              {data.generatedByUserName ? ` · ${data.generatedByUserName}` : ''} ·{' '}
              {data.generatedAt.toISOString()}
            </div>
            <div className="mt-1">
              This snapshot is a point-in-time export. Status is computed by{' '}
              <code>@dnca/domain.statusFor()</code> — the same logic that protects the platform's
              database write path. Identical numbers to the live Currency Tracker.
            </div>
          </footer>
        </article>
      </div>
    </>
  );
}

function PrintToolbar({
  asOf,
  operatorTradingName,
}: {
  asOf: IsoDate;
  operatorTradingName: string;
}) {
  return (
    <div className="no-print sticky top-0 z-10 border-b border-slate-200 bg-amber-50 px-4 py-2 text-xs">
      <div className="mx-auto flex max-w-3xl items-center justify-between gap-3">
        <div className="text-amber-900">
          <strong>{operatorTradingName}</strong> — {asOf}. Use{' '}
          <kbd className="rounded bg-amber-200 px-1">⌘P</kbd>/
          <kbd className="rounded bg-amber-200 px-1">Ctrl+P</kbd> to save as PDF. Margins:{' '}
          <em>none</em>; layout: <em>portrait</em>; scale: <em>100%</em>.
        </div>
        <div className="flex gap-2">
          {DEMO_OPERATORS.map((op) => (
            <a
              key={op.id}
              href={`?operatorId=${op.id}`}
              className="rounded border border-amber-300 bg-white px-2 py-1 text-amber-900 hover:bg-amber-100"
            >
              {op.tradingName}
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}

function PilotSection({ block }: { block: PilotBlock }) {
  return (
    <section className="snapshot-pilot mt-4">
      <h2 className="bg-navy-900 px-2 py-1 text-[11px] font-bold text-white">
        {block.pilot.fullName}
      </h2>
      <div className="bg-slate-100 px-2 py-1 text-[10px] text-slate-700">
        {block.pilot.role} · {block.pilot.licenceNumber} · Base {block.pilot.baseIcao} · Phase{' '}
        {block.pilot.phase.replace(/_/g, ' ')}{' '}
        <span className="ml-2 text-slate-500">
          ({block.statusCounts.CURRENT} current · {block.statusCounts.CAUTION} caution ·{' '}
          {block.statusCounts.ACTION} action · {block.statusCounts.EXPIRED} expired ·{' '}
          {block.statusCounts.NOT_APPLICABLE} N/A)
        </span>
      </div>
      {block.categories.map((c) => (
        <CategoryTable key={c.category} block={c} />
      ))}
    </section>
  );
}

function CategoryTable({ block }: { block: CategoryBlock }) {
  return (
    <div className="mt-2">
      <div className="text-[9px] font-bold uppercase tracking-wide text-slate-600">
        {block.category}
      </div>
      <table className="mt-1 w-full border-collapse text-[10px]">
        <thead>
          <tr className="border-b border-slate-400 bg-slate-100 text-left text-[8px] uppercase tracking-wide text-slate-600">
            <th className="w-[45%] py-1 pl-1">Currency</th>
            <th className="w-[17%] py-1">Valid From</th>
            <th className="w-[17%] py-1">Valid To</th>
            <th className="w-[21%] py-1 pr-1 text-right">Status</th>
          </tr>
        </thead>
        <tbody>
          {block.rows.map((r) => (
            <Row key={r.kind} row={r} />
          ))}
        </tbody>
      </table>
    </div>
  );
}

function Row({ row }: { row: CurrencyRow }) {
  const styles: Record<CurrencyRow['status'], string> = {
    CURRENT: 'bg-emerald-100 text-emerald-800',
    CAUTION: 'bg-amber-100 text-amber-800',
    ACTION: 'bg-red-100 text-red-800',
    EXPIRED: 'bg-red-600 text-white',
    NOT_APPLICABLE: 'bg-slate-200 text-slate-600',
  };
  const label: Record<CurrencyRow['status'], string> = {
    CURRENT: 'Current',
    CAUTION: 'Caution',
    ACTION: 'Action',
    EXPIRED: 'Expired',
    NOT_APPLICABLE: 'N/A',
  };
  return (
    <tr className="border-b border-slate-200">
      <td className="py-1 pl-1">{row.label}</td>
      <td className="py-1">{row.validFrom ?? '—'}</td>
      <td className="py-1">{row.validTo ?? '—'}</td>
      <td className="py-1 pr-1 text-right">
        <span
          className={`inline-block rounded px-2 py-0.5 text-[8px] font-bold ${styles[row.status]}`}
        >
          {label[row.status]}
        </span>
      </td>
    </tr>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-[8px] uppercase tracking-wide text-slate-500">{label}</div>
      <div className="font-bold text-navy-900">{value}</div>
    </div>
  );
}

function PrintStyle() {
  return (
    <style
      // Inline rather than imported so the page works without a separate CSS asset.
      dangerouslySetInnerHTML={{
        __html: `
@media print {
  .no-print { display: none !important; }
  body { background: white !important; }
  .snapshot-pilot { break-inside: avoid; }
  @page {
    size: A4 portrait;
    margin: 12mm 14mm;
  }
}
        `,
      }}
    />
  );
}
