import { DEMO_OM_MAPPINGS, DEMO_OPERATORS, type IsoDate, type OperatorId } from '@dnca/domain';
import {
  buildOmCrossReferenceMatrix,
  type OmMatrixRow,
  type OmMatrixSectionTotals,
} from '@dnca/exports';

export const dynamic = 'force-dynamic';

interface PageProps {
  searchParams: Promise<{ operatorId?: string }>;
}

export default async function OmCrossReferenceMatrixPage({ searchParams }: PageProps) {
  const { operatorId } = await searchParams;
  const operator =
    (operatorId
      ? DEMO_OPERATORS.find((o) => o.id === (operatorId as OperatorId))
      : DEMO_OPERATORS[0]) ?? DEMO_OPERATORS[0]!;
  const asOfDate = new Date();
  const asOf = asOfDate.toISOString().slice(0, 10) as IsoDate;
  const data = buildOmCrossReferenceMatrix({
    operator,
    mappings: DEMO_OM_MAPPINGS,
    asOf,
    generatedAt: asOfDate,
  });

  return (
    <>
      <PrintStyle />
      <div className="print-root font-sans text-slate-800">
        <PrintToolbar asOf={asOf} operatorTradingName={operator.tradingName} />
        <article className="matrix mx-auto max-w-4xl bg-white p-10 print:m-0 print:max-w-none print:p-0">
          <header className="flex items-end justify-between border-b-2 border-amber-500 pb-3">
            <div>
              <h1 className="text-lg font-bold text-navy-900">DN Consultancy Aviation</h1>
              <div className="text-[10px] text-slate-600">
                Fokker 70/100 Flight Crew Training Suite · KCARs 2025-aligned
              </div>
            </div>
            <div className="text-right">
              <div className="text-sm font-bold text-navy-900">OM CROSS-REFERENCE MATRIX</div>
              <div className="text-[10px] text-slate-600">LN 42/2026 Third Schedule</div>
              <div className="text-[10px] text-slate-600">As of {data.asOf}</div>
            </div>
          </header>

          <section className="my-4 grid grid-cols-2 gap-x-6 gap-y-2 rounded bg-slate-100 px-4 py-3 text-[11px]">
            <Meta label="Operator" value={data.operator.legalName} />
            <Meta label="AOC No." value={data.operator.aocNumber} />
            <Meta label="Accountable Manager" value={data.operator.accountableManagerName} />
            <Meta
              label="Submission status"
              value={`§2.1: ${data.totals.section21.mapped}/${data.totals.section21.total} mapped · §2.2: ${data.totals.section22.mapped}/${data.totals.section22.total} mapped`}
            />
          </section>

          <section className="mb-4 rounded border border-slate-200 p-3 text-[10px] leading-relaxed text-slate-700">
            <strong>Attestation purpose.</strong> LN 42/2026 Reg 17(3) requires that an operator's
            Operations Manual address every clause in the Third Schedule before submission to KCAA.
            This matrix is the structured attestation: each binding clause is mapped to the specific
            OM section that addresses it, with an evidence pointer the inspector can verify. Rows
            marked <em>not yet mapped</em> are Phase-1 Compliance Package deliverables. Rows marked{' '}
            <em>subject pending</em> indicate a clause whose contents have not yet been verified
            against the gazetted PDF — to be completed before this matrix is submitted.
          </section>

          <Section
            title="§2.1 — Operations Manual content list"
            subtitle={`${data.totals.section21.total} binding clauses · ${data.totals.section21.subjectVerified} subject-verified · ${data.totals.section21.mapped} mapped to OM`}
            rows={data.section21}
          />

          <Section
            title="§2.2 — Mandatory training topics"
            subtitle={`${data.totals.section22.total} topics · ${data.totals.section22.subjectVerified} subject-verified · ${data.totals.section22.mapped} mapped to OM`}
            rows={data.section22}
          />

          <footer className="mt-8 border-t border-slate-200 pt-3 text-[9px] text-slate-500">
            <div>
              Generated by DNCA Fokker Training Suite
              {data.generatedByUserName ? ` · ${data.generatedByUserName}` : ''} ·{' '}
              {data.generatedAt.toISOString()}
            </div>
            <div className="mt-1">
              Submission discipline: per <strong>LN 42/2026 Reg 17(3)</strong>, this attestation
              must be submitted to KCAA at least 30 days before the operator's intended
              implementation date. The DNCA platform calculates the submission deadline from the
              planned implementation date and locks the document version on submission.
            </div>
          </footer>
        </article>
      </div>
    </>
  );
}

function Section({
  title,
  subtitle,
  rows,
}: {
  title: string;
  subtitle: string;
  rows: ReadonlyArray<OmMatrixRow>;
}) {
  return (
    <section className="matrix-section mt-4">
      <header>
        <h2 className="bg-navy-900 px-2 py-1 text-[11px] font-bold text-white">{title}</h2>
        <div className="bg-slate-100 px-2 py-1 text-[10px] text-slate-700">{subtitle}</div>
      </header>
      <table className="mt-1 w-full border-collapse text-[10px]">
        <thead>
          <tr className="border-b border-slate-400 bg-slate-100 text-left text-[8px] uppercase tracking-wide text-slate-600">
            <th className="w-[8%] py-1 pl-1">Ref</th>
            <th className="w-[32%] py-1">Subject (per gazetted PDF)</th>
            <th className="w-[30%] py-1">Operator OM section</th>
            <th className="w-[20%] py-1">Evidence</th>
            <th className="w-[10%] py-1 pr-1 text-right">Status</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <Row key={row.clause.shortRef} row={row} />
          ))}
        </tbody>
      </table>
    </section>
  );
}

function Row({ row }: { row: OmMatrixRow }) {
  const subject = row.clause.subject;
  const subjectClass = subject === null ? 'italic text-slate-400' : 'text-slate-800';
  const subjectText = subject ?? 'Subject pending primary-source verification (LN 42/2026 PDF)';
  const mapping = row.mapping;
  return (
    <tr className="border-b border-slate-200">
      <td className="py-1 pl-1 font-medium text-slate-700">{row.clause.shortRef}</td>
      <td className={`py-1 ${subjectClass}`}>
        {subjectText}
        {row.clause.notes ? (
          <div className="text-[9px] italic text-slate-500">{row.clause.notes}</div>
        ) : null}
      </td>
      <td className="py-1">
        {mapping ? (
          <span className="text-slate-800">{mapping.operatorOmSection}</span>
        ) : (
          <span className="italic text-slate-400">Not yet mapped (Phase 1)</span>
        )}
      </td>
      <td className="py-1 text-slate-700">{mapping?.evidenceReference ?? (mapping ? '—' : '')}</td>
      <td className="py-1 pr-1 text-right">
        <StatusBadge mapping={mapping} subjectPending={row.clause.pendingPrimarySource} />
      </td>
    </tr>
  );
}

function StatusBadge({
  mapping,
  subjectPending,
}: {
  mapping: OmCrossReferenceMappingForBadge | null;
  subjectPending: boolean;
}) {
  if (mapping !== null) {
    return (
      <span className="inline-block rounded bg-emerald-100 px-2 py-0.5 text-[8px] font-bold text-emerald-800">
        Mapped
      </span>
    );
  }
  if (subjectPending) {
    return (
      <span className="inline-block rounded bg-slate-200 px-2 py-0.5 text-[8px] font-bold text-slate-700">
        Pending
      </span>
    );
  }
  return (
    <span className="inline-block rounded bg-amber-100 px-2 py-0.5 text-[8px] font-bold text-amber-800">
      To map
    </span>
  );
}

// Minimal shape required by StatusBadge — avoids cyclic prop typing.
type OmCrossReferenceMappingForBadge = { readonly operatorOmSection: string };

function PrintToolbar({
  asOf,
  operatorTradingName,
}: {
  asOf: IsoDate;
  operatorTradingName: string;
}) {
  return (
    <div className="no-print sticky top-0 z-10 border-b border-slate-200 bg-amber-50 px-4 py-2 text-xs">
      <div className="mx-auto flex max-w-4xl items-center justify-between gap-3">
        <div className="text-amber-900">
          <strong>{operatorTradingName}</strong> — {asOf}. Use{' '}
          <kbd className="rounded bg-amber-200 px-1">⌘P</kbd>/
          <kbd className="rounded bg-amber-200 px-1">Ctrl+P</kbd> to save as PDF. Margins:{' '}
          <em>narrow</em>; layout: <em>portrait</em>; scale: <em>100%</em>.
        </div>
        <div className="flex gap-2">
          {DEMO_OPERATORS.map((op) => (
            <a
              key={op.id}
              href={`?operatorId=${op.id}`}
              className="rounded border border-amber-300 bg-white px-2 py-1 text-amber-900 hover:bg-amber-100"
            >
              {op.tradingName}
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-[8px] uppercase tracking-wide text-slate-500">{label}</div>
      <div className="font-bold text-navy-900">{value}</div>
    </div>
  );
}

function PrintStyle() {
  return (
    <style
      dangerouslySetInnerHTML={{
        __html: `
@media print {
  .no-print { display: none !important; }
  body { background: white !important; }
  .matrix-section { break-inside: auto; }
  @page {
    size: A4 portrait;
    margin: 10mm 12mm;
  }
}
        `,
      }}
    />
  );
}
