-- ============================================================================
-- Migration 0001: initial schema, RLS policies, append-only audit log.
--
-- Bootstrap migration for the Fokker 70/100 Flight Crew Training Suite.
-- Implements:
--   - Postgres enum types matching @dnca/domain enums
--   - All tenant-scoped tables with operator_id FK
--   - Row-level security policies (ADR 0002)
--   - Append-only audit-log triggers (ADR 0003)
--   - updated_at maintenance triggers
--
-- This is the only migration to live as hand-written SQL; subsequent migrations
-- are generated by drizzle-kit from packages/db/src/schema/ and reviewed in PR.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime') THEN
    CREATE ROLE app_runtime LOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'platform_admin') THEN
    CREATE ROLE platform_admin LOGIN BYPASSRLS;
  END IF;
END$$;

-- ---------------------------------------------------------------------------
-- Enums (must match @dnca/domain constants)
-- ---------------------------------------------------------------------------

CREATE TYPE pilot_role AS ENUM ('Captain', 'First Officer');

CREATE TYPE training_phase AS ENUM (
  'ITR_Ground', 'ITR_FBT', 'ITR_FFS', 'SkillsTest', 'BaseTraining',
  'LIFUS', 'Line', 'RecurrentDue', 'Suspended'
);

CREATE TYPE currency_category AS ENUM ('Personal', 'Type', 'Operational', 'Safety', 'Special');

CREATE TYPE currency_kind AS ENUM (
  'class1Medical', 'atplCpl', 'elpLevel', 'passportVisa',
  'typeRating', 'opc', 'lpc',
  'lineCheck', 'recurrentGround', 'crmTem', 'dangerousGoods', 'aviationSecurity',
  'aerodromeQualification', 'routeQualification', 'picRecency90Day',
  'sepWetDry',
  'rvsm', 'egpwsTaws', 'windshear', 'uprt', 'catII', 'catIII', 'crewPairing'
);

CREATE TYPE currency_status AS ENUM ('CURRENT', 'CAUTION', 'ACTION', 'EXPIRED', 'NOT_APPLICABLE');

CREATE TYPE icao_competency AS ENUM (
  'APPLICATION_OF_PROCEDURES', 'COMMUNICATION',
  'FLIGHT_PATH_AUTOMATION', 'FLIGHT_PATH_MANUAL',
  'LEADERSHIP_TEAMWORK', 'PROBLEM_SOLVING_DECISION_MAKING',
  'SITUATION_AWARENESS', 'WORKLOAD_MANAGEMENT'
);

CREATE TYPE operator_grade AS ENUM ('AS', 'S', 'MS', 'BS');
CREATE TYPE grade_scale AS ENUM ('AS-S-MS-BS', 'ICAO-1-5', 'NOT_OBSERVED');

CREATE TYPE session_kind AS ENUM (
  'ITR_GROUND', 'ITR_FBT', 'ITR_FFS', 'SKILLS_TEST', 'BASE_TRAINING',
  'LIFUS', 'LINE_CHECK', 'OPC', 'LPC',
  'CRM_RECURRENT', 'SEP_RECURRENT', 'GROUND_RECURRENT'
);
CREATE TYPE session_venue AS ENUM ('FFS', 'FBT', 'CLASSROOM', 'AIRCRAFT', 'ONLINE');
CREATE TYPE session_status AS ENUM ('DRAFT', 'COMPLETED', 'SIGNED_OFF', 'VOIDED');

CREATE TYPE sign_off_role AS ENUM ('TRI', 'TRE', 'LCE', 'LTC', 'HOT');

CREATE TYPE document_kind AS ENUM (
  'OM_A', 'OM_B', 'OM_C', 'OM_D',
  'TRAINING_PROGRAMME_ITR', 'TRAINING_PROGRAMME_RECURRENT',
  'CHECKLIST', 'QRH_OPERATOR_SUPPLEMENT', 'TECHNICAL_LOG_TEMPLATE',
  'KCAA_TRANSMITTAL', 'OTHER'
);

CREATE TYPE document_version_status AS ENUM (
  'DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED',
  'RETURNED_FOR_REVISION', 'SUPERSEDED', 'WITHDRAWN'
);

CREATE TYPE user_role AS ENUM (
  'ACCOUNTABLE_MANAGER', 'HEAD_OF_TRAINING', 'CHIEF_PILOT',
  'SAFETY_MANAGER', 'QUALITY_MANAGER',
  'TRI', 'TRE', 'LCE', 'LTC', 'PILOT', 'PLATFORM_ADMIN'
);

CREATE TYPE audit_action AS ENUM (
  'CREATE', 'UPDATE', 'SOFT_DELETE', 'HARD_DELETE',
  'SIGN_OFF', 'EXPORT', 'ASSESSMENT_GENERATED',
  'KCAA_SUBMISSION_LOCKED', 'KCAA_SUBMISSION_APPROVED', 'KCAA_SUBMISSION_REJECTED',
  'AUTH_LOGIN', 'AUTH_LOGIN_FAILED', 'AUTH_LOGOUT', 'AUTH_PASSWORD_RESET',
  'ROLE_GRANTED', 'ROLE_REVOKED'
);

CREATE TYPE operator_status AS ENUM ('active', 'inactive', 'archived');
CREATE TYPE fleet_variant AS ENUM ('F70', 'F70-HGW', 'F100');

-- ---------------------------------------------------------------------------
-- updated_at helper
-- ---------------------------------------------------------------------------

CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- operators
-- ---------------------------------------------------------------------------

CREATE TABLE operators (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  legal_name text NOT NULL,
  trading_name text NOT NULL,
  short_code text NOT NULL UNIQUE,
  aoc_number text NOT NULL,
  country_iso2 text NOT NULL DEFAULT 'KE',
  odpc_registration_number text,
  accountable_manager_name text NOT NULL,
  accountable_manager_email text NOT NULL,
  status operator_status NOT NULL DEFAULT 'active',
  config jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE TRIGGER operators_updated_at BEFORE UPDATE ON operators
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- fleets, aircraft
-- ---------------------------------------------------------------------------

CREATE TABLE fleets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  variant fleet_variant NOT NULL,
  display_name text NOT NULL,
  active boolean NOT NULL DEFAULT true
);
CREATE INDEX fleets_operator_idx ON fleets(operator_id);

CREATE TABLE aircraft (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  fleet_id uuid NOT NULL REFERENCES fleets(id) ON DELETE RESTRICT,
  registration text NOT NULL,
  variant fleet_variant NOT NULL,
  mtow_kg integer NOT NULL,
  mlw_kg integer NOT NULL,
  mzfw_kg integer NOT NULL,
  serial_number text,
  delivered_on date,
  active boolean NOT NULL DEFAULT true
);
CREATE INDEX aircraft_operator_idx ON aircraft(operator_id);
CREATE UNIQUE INDEX aircraft_registration_ux ON aircraft(operator_id, registration);

-- ---------------------------------------------------------------------------
-- users (global), role_assignments (per operator)
-- ---------------------------------------------------------------------------

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX users_email_idx ON users(email);
CREATE TRIGGER users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE role_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  operator_id uuid REFERENCES operators(id) ON DELETE RESTRICT,
  role user_role NOT NULL,
  granted_by_user_id uuid NOT NULL,
  granted_at timestamptz NOT NULL DEFAULT NOW(),
  revoked_at timestamptz
);
CREATE INDEX role_assignments_user_operator_idx ON role_assignments(user_id, operator_id);
CREATE INDEX role_assignments_active_idx ON role_assignments(user_id, role) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- pilots
-- ---------------------------------------------------------------------------

CREATE TABLE pilots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  fleet_id uuid NOT NULL REFERENCES fleets(id) ON DELETE RESTRICT,
  full_name text NOT NULL,
  licence_number text NOT NULL,
  role pilot_role NOT NULL,
  base_icao text NOT NULL,
  phase training_phase NOT NULL,
  employee_id text,
  hire_date date,
  date_of_birth date,
  total_hours integer,
  type_hours integer,
  pic_hours integer,
  emergency_contact_name text,
  emergency_contact_phone text,
  active boolean NOT NULL DEFAULT true,
  deleted_at timestamptz,
  deletion_reason text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX pilots_operator_idx ON pilots(operator_id);
CREATE UNIQUE INDEX pilots_licence_ux ON pilots(operator_id, licence_number);
CREATE TRIGGER pilots_updated_at BEFORE UPDATE ON pilots
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- sessions, exercises, competency_grades, sign_offs, debrief_notes,
-- assessment_results
-- ---------------------------------------------------------------------------

CREATE TABLE sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  pilot_id uuid NOT NULL REFERENCES pilots(id) ON DELETE RESTRICT,
  kind session_kind NOT NULL,
  venue session_venue NOT NULL,
  started_at timestamptz NOT NULL,
  ended_at timestamptz,
  aircraft_id uuid REFERENCES aircraft(id) ON DELETE SET NULL,
  ffs_designation text,
  instructor_user_id uuid NOT NULL,
  paired_pilot_id uuid REFERENCES pilots(id) ON DELETE SET NULL,
  overall_grade_scale grade_scale,
  overall_grade_value text,
  status session_status NOT NULL DEFAULT 'DRAFT',
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX sessions_pilot_idx ON sessions(pilot_id);
CREATE INDEX sessions_operator_idx ON sessions(operator_id);
CREATE INDEX sessions_started_at_idx ON sessions(started_at);
CREATE TRIGGER sessions_updated_at BEFORE UPDATE ON sessions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE exercises (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  ordinal integer NOT NULL,
  title text NOT NULL,
  reference text NOT NULL,
  observable_behaviours jsonb,
  debrief_note text,
  created_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX exercises_session_ordinal_ux ON exercises(session_id, ordinal);
CREATE INDEX exercises_operator_idx ON exercises(operator_id);

CREATE TABLE competency_grades (
  exercise_id uuid NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  competency icao_competency NOT NULL,
  scale grade_scale NOT NULL,
  value text,
  not_observed_reason text,
  PRIMARY KEY (exercise_id, competency)
);
CREATE INDEX competency_grades_operator_idx ON competency_grades(operator_id);

CREATE TABLE sign_offs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES sessions(id) ON DELETE RESTRICT,
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  signed_by_user_id uuid NOT NULL,
  signed_by_role sign_off_role NOT NULL,
  signed_at timestamptz NOT NULL DEFAULT NOW(),
  statement text NOT NULL
);

CREATE TABLE debrief_notes (
  session_id uuid PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  authored_by_user_id uuid NOT NULL,
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX debrief_notes_operator_idx ON debrief_notes(operator_id);

CREATE TABLE assessment_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  pilot_id uuid NOT NULL REFERENCES pilots(id) ON DELETE RESTRICT,
  topic text NOT NULL,
  questions_count integer NOT NULL,
  correct_count integer NOT NULL,
  score_percent integer NOT NULL,
  passed boolean NOT NULL,
  pass_mark_percent integer NOT NULL DEFAULT 80,
  model_id text NOT NULL,
  prompt_version text NOT NULL,
  response_json_hash text NOT NULL,
  taken_at timestamptz NOT NULL DEFAULT NOW(),
  proctored_by_user_id uuid
);
CREATE INDEX assessment_results_pilot_idx ON assessment_results(pilot_id);
CREATE INDEX assessment_results_operator_idx ON assessment_results(operator_id);

-- ---------------------------------------------------------------------------
-- currency_records (FK to sessions added after sessions table)
-- ---------------------------------------------------------------------------

CREATE TABLE currency_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  pilot_id uuid NOT NULL REFERENCES pilots(id) ON DELETE RESTRICT,
  kind currency_kind NOT NULL,
  valid_from date NOT NULL,
  valid_to date NOT NULL,
  source_session_id uuid REFERENCES sessions(id) ON DELETE SET NULL,
  issued_by_user_id uuid,
  notes text,
  attachment_urls jsonb,
  superseded_at timestamptz,
  superseded_by uuid REFERENCES currency_records(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX currency_records_pilot_kind_idx ON currency_records(pilot_id, kind);
CREATE INDEX currency_records_operator_idx ON currency_records(operator_id);
CREATE INDEX currency_records_valid_to_idx ON currency_records(valid_to);

-- ---------------------------------------------------------------------------
-- documents, document_versions, document_pages, kcaa_submissions
-- ---------------------------------------------------------------------------

CREATE TABLE documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  kind document_kind NOT NULL,
  title text NOT NULL,
  short_code text NOT NULL,
  owner_user_id uuid NOT NULL,
  current_version_id uuid,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX documents_operator_short_code_ux ON documents(operator_id, short_code);
CREATE TRIGGER documents_updated_at BEFORE UPDATE ON documents
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE document_versions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  version_label text NOT NULL,
  status document_version_status NOT NULL DEFAULT 'DRAFT',
  content_hash text NOT NULL,
  planned_implementation_date date,
  submission_deadline date,
  submitted_at timestamptz,
  approved_at timestamptz,
  created_by_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX document_versions_document_idx ON document_versions(document_id);
CREATE INDEX document_versions_status_idx ON document_versions(status);
CREATE TRIGGER document_versions_updated_at BEFORE UPDATE ON document_versions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Backfill the documents.current_version_id FK now that document_versions exists.
ALTER TABLE documents
  ADD CONSTRAINT documents_current_version_fk
  FOREIGN KEY (current_version_id) REFERENCES document_versions(id) ON DELETE SET NULL;

CREATE TABLE document_pages (
  document_version_id uuid NOT NULL REFERENCES document_versions(id) ON DELETE CASCADE,
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  page_number integer NOT NULL,
  revision_label text NOT NULL,
  last_revised_at timestamptz NOT NULL,
  content_hash text NOT NULL,
  PRIMARY KEY (document_version_id, page_number)
);
CREATE INDEX document_pages_operator_idx ON document_pages(operator_id);

CREATE TABLE kcaa_submissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid NOT NULL REFERENCES operators(id) ON DELETE RESTRICT,
  document_version_id uuid NOT NULL REFERENCES document_versions(id) ON DELETE RESTRICT,
  submitted_by_user_id uuid NOT NULL,
  submitted_at timestamptz NOT NULL DEFAULT NOW(),
  transmittal_letter_url text NOT NULL,
  receipt_number text,
  reviewer_officer text,
  approved_at timestamptz,
  rejected_at timestamptz,
  rejection_reason text
);

-- ---------------------------------------------------------------------------
-- audit_events — append-only (ADR 0003)
-- ---------------------------------------------------------------------------

CREATE TABLE audit_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  operator_id uuid REFERENCES operators(id) ON DELETE RESTRICT,
  actor_user_id uuid,
  actor_role user_role,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  action audit_action NOT NULL,
  before_state jsonb,
  after_state jsonb,
  occurred_at timestamptz NOT NULL DEFAULT NOW(),
  request_id text NOT NULL,
  ip_address text NOT NULL,
  user_agent text
);
CREATE INDEX audit_events_operator_idx ON audit_events(operator_id);
CREATE INDEX audit_events_entity_idx ON audit_events(entity_type, entity_id);
CREATE INDEX audit_events_occurred_at_idx ON audit_events(occurred_at);
CREATE INDEX audit_events_actor_idx ON audit_events(actor_user_id);

-- Append-only enforcement: reject UPDATE and DELETE regardless of role.
-- Break-glass procedure (out-of-band superuser session) is documented in
-- docs/audit/break-glass-audit-log.md.
CREATE FUNCTION audit_event_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_events is append-only; UPDATE and DELETE are forbidden';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_events_no_update
  BEFORE UPDATE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION audit_event_immutable();

CREATE TRIGGER audit_events_no_delete
  BEFORE DELETE ON audit_events
  FOR EACH ROW EXECUTE FUNCTION audit_event_immutable();

CREATE TRIGGER audit_events_no_truncate
  BEFORE TRUNCATE ON audit_events
  FOR EACH STATEMENT EXECUTE FUNCTION audit_event_immutable();

-- ---------------------------------------------------------------------------
-- Row-level security (ADR 0002)
--
-- Every tenant-scoped table:
--   1. Enables RLS.
--   2. Adds a policy scoping rows to current_setting('app.operator_id').
--
-- Unscoped queries (no SET LOCAL app.operator_id) see zero rows — the safe
-- default. The platform_admin role has BYPASSRLS for cross-tenant operations
-- which are individually audited.
-- ---------------------------------------------------------------------------

CREATE FUNCTION current_operator_id() RETURNS uuid AS $$
  SELECT NULLIF(current_setting('app.operator_id', true), '')::uuid;
$$ LANGUAGE sql STABLE;

DO $$
DECLARE
  tbl text;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'fleets', 'aircraft', 'pilots',
    'sessions', 'exercises', 'competency_grades', 'sign_offs',
    'debrief_notes', 'assessment_results',
    'currency_records',
    'documents', 'document_versions', 'document_pages', 'kcaa_submissions'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', tbl);
    EXECUTE format(
      'CREATE POLICY %I_tenant_isolation ON %I '
      || 'USING (operator_id = current_operator_id()) '
      || 'WITH CHECK (operator_id = current_operator_id())',
      tbl, tbl
    );
  END LOOP;
END$$;

-- Child tables (exercises, competency_grades, debrief_notes, document_pages)
-- carry a denormalised operator_id so the policy is uniform across all
-- tenant-scoped tables. The denormalisation invariant (child.operator_id =
-- parent.operator_id) is enforced by the application's repository layer and
-- verified by an integration test against seeded fixtures.

-- audit_events also carries RLS. operator_id is nullable (global/pre-auth
-- events such as AUTH_LOGIN_FAILED have no operator yet), so it is excluded
-- from the loop above and given bespoke policies here:
--
--   * SELECT is scoped to the current operator. A tenant session sees only its
--     own operator's events. Global (operator_id IS NULL) and cross-tenant
--     events are visible only to platform_admin, which has BYPASSRLS — this is
--     the "cross-tenant queries restricted to platform-admin" rule (CLAUDE.md
--     §"Multi-tenancy" / §"Audit logging"). Without this policy, app_runtime —
--     which holds GRANT SELECT below — could read every operator's audit trail,
--     including PII in before_state/after_state.
--   * INSERT permits the current operator's rows and global (NULL) rows so the
--     auth layer can record pre-auth events. UPDATE/DELETE have no policy and
--     are additionally blocked by the append-only triggers and the REVOKE below.
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
CREATE POLICY audit_events_tenant_read ON audit_events
  FOR SELECT
  USING (operator_id = current_operator_id());
CREATE POLICY audit_events_tenant_insert ON audit_events
  FOR INSERT
  WITH CHECK (operator_id = current_operator_id() OR operator_id IS NULL);

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

GRANT USAGE ON SCHEMA public TO app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO app_runtime;

-- audit_events explicitly grants INSERT only (UPDATE/DELETE are trigger-
-- rejected, but defence-in-depth keeps the permission off too).
REVOKE UPDATE, DELETE, TRUNCATE ON audit_events FROM app_runtime;
